---

- name: Manage sysstat cron configration
  ansible.builtin.template:
    src: sysstat.cron.j2
    dest: "{{ sysstat_config_cronpath }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Sleep sysstat
    - Restart crond
  when: sysstat_config_crondata is defined and sysstat_config_crondata
