---

- name: Install tasks
  become: true
  tags:
    - sysstat_install
    - sysstat
  block:
    - name: Install sysstat package
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name: "{{ sysstat_package_name }}"
        state: "{{ sysstat_package_ensure }}"
        update_cache: true
    - name: Install sysstat package
      when: ansible_os_family == 'RedHat'
      ansible.builtin.yum:
        name: "{{ sysstat_package_name }}"
        state: "{{ sysstat_package_ensure }}"
